"""initial schema

Revision ID: 444181f9699d
Revises: 
Create Date: 2026-09-24 11:38:30.655889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '444181f9699d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'operator', 'readonly', name='roleenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_users_id'), 'api_users', ['id'], unique=False)
    op.create_index(op.f('ix_api_users_username'), 'api_users', ['username'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_cpf'), 'usuarios', ['cpf'], unique=True)
    op.create_index(op.f('ix_usuarios_data_nascimento'), 'usuarios', ['data_nascimento'], unique=False)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_nome'), 'usuarios', ['nome'], unique=False)
    op.create_index(op.f('ix_usuarios_telefone'), 'usuarios', ['telefone'], unique=False)
    op.create_table('enderecos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('logradouro', sa.String(length=150), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_endereco_vizinhanca', 'enderecos', ['bairro', 'logradouro', 'numero'], unique=False)
    op.create_index(op.f('ix_enderecos_bairro'), 'enderecos', ['bairro'], unique=False)
    op.create_index(op.f('ix_enderecos_id'), 'enderecos', ['id'], unique=False)
    op.create_index(op.f('ix_enderecos_logradouro'), 'enderecos', ['logradouro'], unique=False)
    op.create_index(op.f('ix_enderecos_numero'), 'enderecos', ['numero'], unique=False)
    op.create_table('parentescos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('related_user_id', sa.Integer(), nullable=False),
    sa.Column('grau', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['related_user_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'related_user_id', name='uq_relacionamento')
    )
    op.create_index(op.f('ix_parentescos_id'), 'parentescos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parentescos_id'), table_name='parentescos')
    op.drop_table('parentescos')
    op.drop_index(op.f('ix_enderecos_numero'), table_name='enderecos')
    op.drop_index(op.f('ix_enderecos_logradouro'), table_name='enderecos')
    op.drop_index(op.f('ix_enderecos_id'), table_name='enderecos')
    op.drop_index(op.f('ix_enderecos_bairro'), table_name='enderecos')
    op.drop_index('idx_endereco_vizinhanca', table_name='enderecos')
    op.drop_table('enderecos')
    op.drop_index(op.f('ix_usuarios_telefone'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_nome'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_data_nascimento'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_cpf'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_api_users_username'), table_name='api_users')
    op.drop_index(op.f('ix_api_users_id'), table_name='api_users')
    op.drop_table('api_users')
    # ### end Alembic commands ###
